[package]
name = "raytrace"
version = "0.1.0"
authors = ["Sven Liefgen <sven@liefgen.lu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
